### ISSUE TITLE
Why does Bob need an ETH address in the CLI?

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1888] opened 2020-04-15 01:37 UTC
In the CLI, Bob is required to choose an ETH address, although frequently we talk about about Bob being _not blockchainy_.

For other characters, being not federated directly implies they are blockchainy. But, is this also true for Bob?

**Comment by KPrasch** [comment] 2021-01-08 23:28
Closing as duplicate of https://github.com/nucypher/nucypher/issues/1051

**Closed by KPrasch** 2021-01-08 23:28 UTC
Labels: Bob 👨‍💼, Documentation, Guidance, duplicate
