### ISSUE TITLE
`ursula` does not run on parity node

### ISSUE THREAD

**Issue by xujiahuayz** [nucypher/nucypher#2407] opened 2020-10-26 23:08 UTC
**The Bug**

`ursula` throws error on a parity node.

**To Reproduce**
The parity node is run on tmux with:
`parity --ipc-apis="eth,net,web3,personal,parity"`

Then in `pipenv shell`, I ran
`nucypher ursula run` 

it shows that worker is bonded and that worker settings are confirmed, but throws error in the end.

**Traceback**

```sh
Unhandled Error
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/nucypher/characters/lawful.py", line 1248, in run
    self.work_tracker.start(act_now=True)  # requirement_func=self._availability_tracker.status)  # TODO: #2277
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/nucypher/blockchain/eth/token.py", line 579, in start
    d = self._tracking_task.start(interval=self.random_interval(), now=act_now)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/twisted/internet/task.py", line 194, in start
    self()
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/twisted/internet/base.py", line 886, in runUntilCurrent
    f(*a, **kw)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/nucypher/blockchain/eth/token.py", line 588, in _crash_gracefully
    failure.raiseException()
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/twisted/python/failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/nucypher/blockchain/eth/token.py", line 644, in _do_work
    self.worker.commit_to_next_period(fire_and_forget=True)  # < --- blockchain WRITE | Do not wait for receipt
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/nucypher/crypto/powers.py", line 141, in __exit__
    return self.lock_account()
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/nucypher/crypto/powers.py", line 184, in lock_account
    self._signer.lock_account(account=self.__account)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/nucypher/blockchain/eth/decorators.py", line 105, in wrapped
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/nucypher/blockchain/eth/signers/software.py", line 94, in lock_account
    result = self.__client.lock_account(account=account)
  File "/home/ubuntu/.local/share/virtualenvs/nucypher-fvStivKV/lib/python3.6/site-packages/nucypher/blockchain/eth/clients.py", line 536, in lock_account
    return self.w3.parity.personal.lock_account(account)
builtins.AttributeError: 'ParityPersonal' object has no attribute 'lock_account'
```

**System:**
 - OS Version:  Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1028-aws x86_64)
 - Nucypher Version: version 4.0.1
 - Ethereum Node Version:  Parity-Ethereum/v2.7.2

I suspect there are bugs around this line of the file:
https://github.com/nucypher/nucypher/blob/3d0e54f3281d93bb98fcd22af0f3cc0629f823e3/nucypher/blockchain/eth/clients.py#L543

**Comment by cygnusv** [comment] 2021-01-04 13:45
The problem is a bit deeper. Parity does not have a `lockAccount` endpoint. See e.g.
https://web3py.readthedocs.io/en/stable/v5_migration.html#removed-methods

In our side, locking accounts is an ingrained step of our TransactingPower and Signer logic. We can either add custom logic for the parity case, or simply deprecate its support. Thoughts?

**Comment by cygnusv** [comment] 2021-01-20 12:28
Wontfix. For the moment we will support Geth-based clients.

**Closed by cygnusv** 2021-01-20 12:28 UTC
Labels: Bug 🐞
