### ISSUE TITLE
Signer unintentionally used as provider

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2218] opened 2020-09-01 18:45 UTC
```
tuxⒶlattice:[~/code/nucypher-kms] => nucypher ursula init --signer ipc:///home/tux/.ethereum/geth.ipc --provider wss://mainnet.infura.io/ws/...
```

Traceback:
```
Traceback (most recent call last):
  File "/home/tux/code/nucypher-kms/nucypher/blockchain/eth/interfaces.py", line 1015, in get_interface
    cached_interface = cls._interfaces[provider_uri]
KeyError: 'ipc:///home/tux/.ethereum/geth.ipc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tux/code/nucypher-kms/nucypher/blockchain/eth/interfaces.py", line 1042, in get_or_create_interface
    interface = cls.get_interface(provider_uri=provider_uri)
  File "/home/tux/code/nucypher-kms/nucypher/blockchain/eth/interfaces.py", line 1017, in get_interface
    raise cls.InterfaceNotInitialized(f"There is no connection for {provider_uri}. "
nucypher.blockchain.eth.interfaces.InterfaceNotInitialized: There is no connection for ipc:///home/tux/.ethereum/geth.ipc. Call .initialize_connection, then try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tux/code/nucypher-kms/venv/bin/nucypher", line 33, in <module>
    sys.exit(load_entry_point('nucypher', 'console_scripts', 'nucypher')())
  File "/home/tux/code/nucypher-kms/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/tux/code/nucypher-kms/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/tux/code/nucypher-kms/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tux/code/nucypher-kms/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tux/code/nucypher-kms/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tux/code/nucypher-kms/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/tux/code/nucypher-kms/nucypher/cli/options.py", line 154, in wrapper
    return func(**kwargs)
  File "/home/tux/code/nucypher-kms/nucypher/cli/options.py", line 154, in wrapper
    return func(**kwargs)
  File "/home/tux/code/nucypher-kms/nucypher/cli/commands/ursula.py", line 322, in init
    ursula_config = config_options.generate_config(emitter, config_root, force)
  File "/home/tux/code/nucypher-kms/nucypher/cli/commands/ursula.py", line 183, in generate_config
    worker_address = select_client_account(emitter=emitter,
  File "/home/tux/code/nucypher-kms/nucypher/cli/actions/select.py", line 116, in select_client_account
    signer = Signer.from_signer_uri(signer_uri)
  File "/home/tux/code/nucypher-kms/nucypher/blockchain/eth/signers.py", line 69, in from_signer_uri
    signer = signer_class.from_signer_uri(uri=uri)
  File "/home/tux/code/nucypher-kms/nucypher/blockchain/eth/signers.py", line 113, in from_signer_uri
    blockchain = BlockchainInterfaceFactory.get_or_create_interface(provider_uri=uri)
  File "/home/tux/code/nucypher-kms/nucypher/blockchain/eth/interfaces.py", line 1045, in get_or_create_interface
    interface = cls.get_interface(provider_uri=provider_uri)
  File "/home/tux/code/nucypher-kms/nucypher/blockchain/eth/interfaces.py", line 1030, in get_interface
    interface.connect()
  File "/home/tux/code/nucypher-kms/nucypher/blockchain/eth/interfaces.py", line 320, in connect
    self.attach_middleware()
  File "/home/tux/code/nucypher-kms/nucypher/blockchain/eth/interfaces.py", line 288, in attach_middleware
    gwei_gas_price = Web3.fromWei(self.client.gas_price_for_transaction(), 'gwei')
  File "/home/tux/code/nucypher-kms/nucypher/blockchain/eth/clients.py", line 289, in gas_price_for_transaction
    return self.w3.eth.generateGasPrice(transaction) or self.gas_price
  File "/home/tux/code/nucypher-kms/venv/lib/python3.8/site-packages/web3/eth.py", line 552, in generateGasPrice
    return self.gasPriceStrategy(self.web3, transaction_params)
  File "/home/tux/code/nucypher-kms/venv/lib/python3.8/site-packages/web3/gas_strategies/time_based.py", line 208, in time_based_gas_price_strategy
    avg_block_time = _get_avg_block_time(web3, sample_size=sample_size)
  File "/home/tux/code/nucypher-kms/venv/lib/python3.8/site-packages/web3/gas_strategies/time_based.py", line 51, in _get_avg_block_time
    raise ValidationError('Constrained sample size is 0')
web3.exceptions.ValidationError: Constrained sample size is 0
```

**Comment by KPrasch** [comment] 2020-09-02 19:26
Here's what's happening:

Only two kinds of signer schemes are currently supported: `clef://` and `keystore://`.  If the signer URI scheme does not exist ( `Signer.from_uri` uses the default of Web3Signer` which is bound to fail, since it has different RPC endpoints.

**Comment by KPrasch** [comment] 2020-09-17 15:29
Not oily rags.

**Comment by KPrasch** [comment] 2020-09-17 20:40
Duplicate of https://github.com/nucypher/nucypher/issues/2243

**Comment by cygnusv** [comment] 2020-10-07 15:30
I think it's not a duplicate of #2243. The error at the end is the same, but the underlying problem here is that the signer is used as provider. When the signer is geth, this usually means using an  unsynced geth as a provider, which causes the `web3.exceptions.ValidationError: Constrained sample size is 0`, but that's a different reason.

**Comment by KPrasch** [comment] 2020-10-07 16:09
I have tried to reproduce it locally, and I think the premise is innaccurate.  It's not that the signer is being used as a provider, it's that there is a gas strategy being used for any kind of interface connection, including the signer API, geth --dev chains, etc.

in other words, a `Web3Signer` is essentially an extension of `BlockchainInterface` and this issue can be fixed by not attaching time based gas strategies when using such interface modes.

**Closed** 2020-10-07 16:17 UTC
