### ISSUE TITLE
Pass proper arguments into policy_agent.contract.functions.createPolicy

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#316] opened 2018-06-17 03:02 UTC
`BlockchainArrangement.publish` passes arguments into `PolicyAgent.contract.functions.createPolicy` that are consistent with a previous contract version and inconsistent with the current one.

**Comment by jMyles** [comment] 2018-07-02 23:29
@KPrasch, @szotov: Still need to pow-wow on this one.

**Comment by KPrasch** [comment] 2018-08-30 11:33
Since we cannot reproduce this Issue any longer - Im closing the ticket.

**Closed by KPrasch** 2018-08-30 11:33 UTC
