### ISSUE TITLE
Requesting Dynamis DNS Support

### ISSUE THREAD

**Issue by greystroke** [nucypher/nucypher#2936] opened 2022-05-05 01:49 UTC
PRE node will only accept a Static IP address.  Would be helpful to have Dynamic DNS support so can provide domain name instead of an IP address which is dynamic for home node operators.

**Comment by KPrasch** [comment] 2022-05-07 14:51
Thanks for the bump.  Closing this issue since it is a duplicate of #1308

**Closed by KPrasch** 2022-05-07 14:51 UTC
Labels: Duplicate
