### ISSUE TITLE
Prevent password prompts in cases of hardware wallets

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#1127] opened 2019-07-18 18:46 UTC
In some places, like `nucypher stake set-worker`, I will be prompted to provide a password despite using a hardware wallet.

**Comment by KPrasch** [comment] 2019-11-22 19:47
Duplicate of https://github.com/nucypher/nucypher/issues/1439?

**Comment by KPrasch** [comment] 2019-12-10 07:56
Closing as duplicate of #1493

**Closed by KPrasch** 2019-12-10 07:56 UTC
Labels: Bug 🐞, CLI, UX
