### ISSUE TITLE
JSONDecodeError during cfrag retrieval on Lynx

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#3006] opened 2022-11-09 15:22 UTC
**Describe the Bug**
```
Traceback (most recent call last):
  File "/Users/derek/Documents/Github/repos/forks/derek/nucypher-porter/porter/controllers.py", line 220, in handle_request
    response = self._perform_action(action=method_name, request=request_body)
  File "/Users/derek/Documents/Github/repos/forks/derek/nucypher-porter/porter/controllers.py", line 43, in _perform_action
    response = method(**params)  # < ---- INLET
  File "/Users/derek/Documents/Github/repos/forks/derek/nucypher-porter/porter/interfaces.py", line 17, in wrapped
    return func(*args, **kwargs)
  File "/Users/derek/Documents/Github/repos/forks/derek/nucypher-porter/porter/interfaces.py", line 68, in retrieve_cfrags
    retrieval_outcomes = self.implementer.retrieve_cfrags(
  File "/Users/derek/Documents/Github/repos/forks/derek/nucypher-porter/porter/main.py", line 167, in retrieve_cfrags
    results, errors = client.retrieve_cfrags(
  File "/Users/derek/.local/share/virtualenvs/nucypher-porter-wF43iFf2/lib/python3.9/site-packages/nucypher/network/retrieval.py", line 309, in retrieve_cfrags
    retrieval_plan = RetrievalPlan(treasure_map=treasure_map, retrieval_kits=retrieval_kits)
  File "/Users/derek/.local/share/virtualenvs/nucypher-porter-wF43iFf2/lib/python3.9/site-packages/nucypher/network/retrieval.py", line 65, in __init__
    self._conditions = list(ConditionLingo.from_list(lingo) if lingo else None for lingo in json_conditions)
  File "/Users/derek/.local/share/virtualenvs/nucypher-porter-wF43iFf2/lib/python3.9/site-packages/nucypher/network/retrieval.py", line 65, in <genexpr>
    self._conditions = list(ConditionLingo.from_list(lingo) if lingo else None for lingo in json_conditions)
  File "/Users/derek/.local/share/virtualenvs/nucypher-porter-wF43iFf2/lib/python3.9/site-packages/nucypher/network/retrieval.py", line 64, in <genexpr>
    json_conditions = (json.loads(str(c)) for c in rust_conditions)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**To Reproduce**
```python
In [13]: payload = {
    ...:   "treasure_map": "VE1hcAABAACVAcQQnn6+59iG7elT3Hqyis1F3IHEFLFdWk4r409L4VShsIqUq5IP/YpBksRiAhJ5IV6sYSrv38p1JuC/R5cRDEm/2YsCw/8C0Ptuk76tAgfZLcwrKM+zmju5BI5fVgbHFdon+uFU79eGDpIELwRqsyN
    ...: /oIc6sGYSckNrX3IW7mh0URFHBDN1FCaSy1uhIGDFAXoFDpxyxwV+px2SC4XukyRYTvNpGnMRYbNbIVnw0ruHEqIKy7+DBQ9KUo4H3vZ5xa5bP/QVWZ/usMpKJ73TM9DT3YJYUSTUnSosHEjndtXHeyMK4pf7QAtGSAighLNoHCJQzk+smX7Pp
    ...: 7ooBMGicaeV1w6N3Tutzy5VDIFALlnuz80V6AN1RUdI5gK/HlkwWhkjDGcrO17tz6dRe+tz6xbo4xt5IBaXTBsY3/UeSu+FW4NxLU7/f41Qm8h8T0mChAKcj2iEHSWSH4AYE8uTaPW408p/WAxSJY3d/8iTYuJQiE+PlUTNEwdV7RLXhkyP1T0
    ...: K/1V9rDl3USxreD5TprLY63ihhwOsNeVQYTm3Ss/xX6wmsln7f5k+KwOjvO4P34RTr6zFFsc1MoX/OWHmTBq0ecRiemBQKwHpOThbHXwY1OPDawDnJr9bFgXhStHCA5QTEJ7YrFWchVAsW37D2bNvK/kGjfEgIxEUSYIYh7efcDBw43ryHNES3
    ...: NPEIQOoST/17Xg6YhTUGfPLMtN7ibIkDIODbClg5SDpa6wm4MQhAtf4w5U+cJ/35w0VLLilK/XPF87H5L782Zg1ivv8CCa4",
    ...:   "retrieval_kits": [
    ...:     "UktpdAABAACTxGIDH/VoL+6TPHw9fsqWiulVKRVfOcY1E/n4ZlnvwhbNSmQDcvDeudjAMLkolfQw9tRFvJpkWlD6SYMWQx5dkBb0/3MXTG4e5Pc7X7o4R7GaMG9K3SSkUPKPHlruQ4pOozGxA5DcANdbeyJjb250cmFjdEFkZHJlc3MiO
    ...: iIweDE4ZGY5ZjZjNjA2QjJDNDQwMEQ2OUVlZWQyNjg0Y2QxQWE1MDFiOEQiLCJjaGFpbiI6IkfMw8y2cmxpIiwic3RhbmRhcmRDb250cmFjdFR5cGUiOiJFUkM3MjEiLCJtZXRob2QiOiJiYWxhbmNlT2YiLCJwYXJhbWV0ZXJzIjpbIjp1c2V
    ...: yQWRkcmVzcyJdLCJyZXR1cm5WYWx1ZVRlc3QiOnsiY29tcGFyYXRvciI6Ij4iLCJ2YWx1ZSI6IjAifX1d"
    ...:   ],
    ...:   "alice_verifying_key": "02d7f8c3953e709ff7e70d152cb8a52bf5cf17cec7e4befcd998358afbfc0826b8",
    ...:   "bob_encrypting_key": "02f1b784f76272e9afaf6e96fb26fddc1b5af2814914d7ef7bed6d0d2d45d17fc8",
    ...:   "bob_verifying_key": "02f1b784f76272e9afaf6e96fb26fddc1b5af2814914d7ef7bed6d0d2d45d17fc8",
    ...:   "context": "{\":userAddress\":{\"signature\":\"0x9f716ee77ae5b3cbddcbcbd17cefc28f6cf40e75f06279c988d3026f6b9703305a212bcbc47e9d64750c3bc8696f4cb2b4e8563a2117f43e560976d3fa9711d71c\
    ...: ",\"typedData\":{\"types\":{\"Wallet\":[{\"name\":\"address\",\"type\":\"address\"},{\"name\":\"signatureText\",\"type\":\"string\"},{\"name\":\"blockNumber\",\"type\":\"uint256\"},{
    ...: \"name\":\"blockHash\",\"type\":\"bytes32\"}],\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"ui
    ...: nt256\"},{\"name\":\"salt\",\"type\":\"bytes32\"}]},\"domain\":{\"name\":\"tDec\",\"version\":\"1\",\"chainId\":5,\"salt\":\"0x2e9dd27c756e223f900fb7304c02cdfe564f200e5eb8bec6a82b81a
    ...: c4a3a153c\"},\"message\":{\"address\":\"0x3B42d26E19FF860bC4dEbB920DD8caA53F93c600\",\"signatureText\":\"I'm the owner of address 0x3B42d26E19FF860bC4dEbB920DD8caA53F93c600 as of blo
    ...: ck number 7915836\",\"blockNumber\":7915836,\"blockHash\":\"0x26f5a2059adb2f202bea07d6b4a4d9d3c8a44c5df67f86a5a65e59f2b4d5f448\"},\"primaryType\":\"Wallet\"},\"address\":\"0x3B42d26E
    ...: 19FF860bC4dEbB920DD8caA53F93c600\"}}"
    ...: }

In [14]: r = requests.post('https://porter-lynx.nucypher.community/retrieve_cfrags', json=payload)
````

**System (please complete the following information):**
 - OS Version:
 - Nucypher Version:
 - Ethereum Node Version:

**Comment by derekpierre** [comment] 2022-11-09 15:33
Possible reason is that `nucypher-ts` uses a different version of `nucypher-core` than `nucypher` (development branch) & `nucypher-porter` (main) code.

**Comment by derekpierre** [comment] 2022-11-09 19:18
Potentially fixed by https://github.com/nucypher/nucypher-ts/pull/107

**Comment by KPrasch** [comment] 2022-11-15 01:50
This issue was caused by running a version of nucypher-ts based on an outdated alpha version of nucypher-core against nodes running with a newer stable version of nucypher-core.  Fixed by  https://github.com/nucypher/nucypher-ts/pull/107

**Closed by KPrasch** 2022-11-15 01:51 UTC
