### ISSUE TITLE
Can't receive the "expect"  password filling automatically for "ucypher stake create"

### ISSUE THREAD

**Issue by likaioc** [nucypher/nucypher#1609] opened 2020-01-22 10:10 UTC
When I execute the following expect command,  the passing inputing is hanging: 
accIndex=5
expect <<EOF
	set timeout 3600
	set password "***********"
	spawn nucypher stake create
	expect "Select staking account*:" { send "*\n" }
	expect "Enter password to unlock account*" { send "$password\n" }
	expect "Enter stake value in NU*" { send "******\n" }
	expect "Enter stake duration*" { send "**\n" }
	expect "Accept ursula node operator obligation*" { send "y\n" }
	expect eof
EOF

and then  it is hanging: 
spawn nucypher stake create

 ____    __            __
/\  _`\ /\ \__        /\ \
\ \,\L\_\ \ ,_\    __ \ \ \/'\      __   _ __
 \/_\__ \\ \ \/  /'__`\\ \ , <    /'__`\/\`'__\
   /\ \L\ \ \ \_/\ \L\.\\ \ \\`\ /\  __/\ \ \/
   \ `\____\ \__\ \__/.\_\ \_\ \_\ \____\\ \_\
    \/_____/\/__/\/__/\/_/\/_/\/_/\/____/ \/_/

The Holder of Stakes.

Enter password to unlock account *********************: ******************

**Comment by KPrasch** [comment] 2020-01-22 20:17
@likaioc - How long does it hang for?  Are you using a hardware wallet that requires button confirmation? 

From what you described it sounds like your ethereum node is trying to broadcast the transaction, perhaps check the logs right after accepting the obligation.

**Comment by likaioc** [comment] 2020-01-23 09:25
It will hang all along until the expect timeout.

No,  I use the software wallet. 

If I input the password manually， there is no hanging stage.  So the ethereum node should be ok.

**Comment by KPrasch** [comment] 2020-10-20 20:04
@likaioc - I cannot reproduce this issue, closing this for now.  Feel free to post back here using a more recent version of nucypher if you have similar problems.

**Closed by KPrasch** 2020-10-20 20:04 UTC
Labels: CLI, Enhancement, UX
