### ISSUE TITLE
AlreadyQuit exception

### ISSUE THREAD

**Issue by tylerdow** [nucypher/nucypher#1862] opened 2020-04-08 08:23 UTC
**Describe the Bug**
I just run my node and see this in my log after few minutes of activity. Node running as a service.

**To Reproduce**
I just ran my node

**Traceback or Screenshots (Optional) **
nucypher[8895]: Unhandled Error
nucypher[8895]: Traceback (most recent call last):
nucypher[8895]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/internet/base.py", line 434, in fireEvent
nucypher[8895]:     DeferredList(beforeResults).addCallback(self._continueFiring)
nucypher[8895]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 322, in addCallback
nucypher[8895]:     callbackKeywords=kw)
nucypher[8895]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
nucypher[8895]:     self._runCallbacks()
nucypher[8895]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
nucypher[8895]:     current.result = callback(current.result, *args, **kw)
nucypher[8895]: --- <exception caught here> ---
nucypher[8895]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/internet/base.py", line 447, in _continueFiring
nucypher[8895]:     callable(*args, **kwargs)
nucypher[8895]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 278, in stop
nucypher[8895]:     self._team.quit()
nucypher[8895]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/_threads/_team.py", line 226, in quit
nucypher[8895]:     self._quit.set()
nucypher[8895]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/_threads/_convenience.py", line 35, in set
nucypher[8895]:     self.check()
nucypher[8895]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/_threads/_convenience.py", line 46, in check
nucypher[8895]:     raise AlreadyQuit()

**System (please complete the following information):**
 - OS Version: Ubuntu 18.04 LTS
 - Nucypher Version: 2.1.0-beta.2
 - Ethereum Node Version:  1.9.7-stable on external node via websocket

**Comment by KPrasch** [comment] 2020-04-08 13:32
Duplicate of #1841

**Comment by KPrasch** [comment] 2020-04-13 17:38
Duplicate of #1292

**Closed by KPrasch** 2020-04-13 17:38 UTC
Labels: Bug 🐞
