### ISSUE TITLE
Save validation and verification state in node storage.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1453] opened 2019-11-10 19:19 UTC
If a `Learner` has already validated metadata or verified a node, there's no reason to do it again at next launch.  Let's keep a flag of verification status in node storage.

**Comment by derekpierre** [comment] 2020-04-09 18:43
Related to #1866  (@jMyles dupe?)

**Comment by KPrasch** [comment] 2020-09-17 20:43
I agree - this is a duplicate of #1866

**Closed by KPrasch** 2020-09-17 20:43 UTC
Labels: BlueOyster🍄, not-premature, performance
