### ISSUE TITLE
Attempt to bond worker to stake failed with exception-within-exception and missing gasPrice

### ISSUE THREAD

**Issue by svenski123** [nucypher/nucypher#2388] opened 2020-10-19 13:46 UTC
Attempt to bond worker to stake resulted in exception-within-exception below; command line and stack trace below.

It would appear some issue occurred during gas price estimation

Note I was subsequently able to the bond the worker so the issue may have been transient however the double exception suggests some error condition is not being handled.
```
$ nucypher stake bond-worker --config-file ~/nucypher/etc/0/stakeholder.json --hw-wallet --staking-address 0xBAc4Cf91090Fddbc72BC41531E092b7462041107 --network mainnet --worker-address 94d1508193E89bb9a74e1F172dC7B1c385E38dA5
Commit to bonding worker 0x94d1508193E89bb9a74e1F172dC7B1c385E38dA5 to staker 0xBAc4Cf91090Fddbc72BC41531E092b7462041107 for a minimum of 2 periods? [y/N]: y
always failing transaction (execution reverted)
Traceback (most recent call last):
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/nucypher/blockchain/eth/interfaces.py", line 528, in build_contract_transaction
    transaction_dict = contract_function.buildTransaction(payload)  # Gas estimation occurs here
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/web3/contract.py", line 1075, in buildTransaction
    return build_transaction_for_function(
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/web3/contract.py", line 1647, in build_transaction_for_function
    prepared_transaction = fill_transaction_defaults(web3, prepared_transaction)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/web3/_utils/transactions.py", line 87, in fill_transaction_defaults
    default_val = default_getter(web3, transaction)
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/web3/_utils/transactions.py", line 55, in <lambda>
    'gas': lambda web3, tx: web3.eth.estimateGas(tx),
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/web3/eth.py", line 448, in estimateGas
    return self.web3.manager.request_blocking(
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/web3/manager.py", line 153, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'always failing transaction (execution reverted)'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krypto/nucypher/bin/nucypher", line 8, in <module>
    sys.exit(nucypher_cli())
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/nucypher/cli/options.py", line 163, in wrapper
    return func(**kwargs)
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/nucypher/cli/options.py", line 163, in wrapper
    return func(**kwargs)
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/nucypher/cli/options.py", line 163, in wrapper
    return func(**kwargs)
  [Previous line repeated 1 more time]
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/nucypher/cli/commands/stake.py", line 405, in bond_worker
    receipt = STAKEHOLDER.bond_worker(worker_address=worker_address)
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/nucypher/blockchain/eth/decorators.py", line 116, in wrapped
    return func(actor, *args, **kwargs)
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/nucypher/blockchain/eth/decorators.py", line 124, in wrapped
    receipt_or_txhash = actor_method(self, *args, **kwargs)
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/nucypher/blockchain/eth/decorators.py", line 105, in wrapped
    return func(*args, **kwargs)
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/nucypher/blockchain/eth/actors.py", line 1314, in bond_worker
    receipt = self.staking_agent.bond_worker(staker_address=self.checksum_address,
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/nucypher/blockchain/eth/decorators.py", line 105, in wrapped
    return func(*args, **kwargs)
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/nucypher/blockchain/eth/agents.py", line 569, in bond_worker
    receipt: TxReceipt = self.blockchain.send_transaction(contract_function=contract_function,
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/nucypher/blockchain/eth/decorators.py", line 105, in wrapped
    return func(*args, **kwargs)
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/nucypher/blockchain/eth/interfaces.py", line 657, in send_transaction
    transaction = self.build_contract_transaction(contract_function=contract_function,
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/nucypher/blockchain/eth/decorators.py", line 105, in wrapped
    return func(*args, **kwargs)
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/nucypher/blockchain/eth/interfaces.py", line 532, in build_contract_transaction
    raise self._handle_failed_transaction(exception=error,
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/nucypher/blockchain/eth/interfaces.py", line 458, in _handle_failed_transaction
    transaction_failed = cls.TransactionFailed(message=message,  # rich error (best case)
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/nucypher/blockchain/eth/interfaces.py", line 125, in __init__
    BlockchainInterface.REASONS[INSUFFICIENT_ETH]: self.insufficient_eth
  File "/home/krypto/nucypher/lib64/python3.8/site-packages/nucypher/blockchain/eth/interfaces.py", line 146, in insufficient_eth
    gas = (self.payload.get('gas', 1) * self.payload['gasPrice'])  # FIXME: If gas is not included...
KeyError: 'gasPrice'
```

**Comment by KPrasch** [comment] 2020-10-20 20:12
Fixed in https://github.com/nucypher/nucypher/pull/2375

**Comment by cygnusv** [comment] 2020-10-20 20:19
This issue should be reopened as it shows 2 things we don't know why are happening:
1. Bond worker fails for some reason. We need to understand why is this happening and be able to reproduce.
2. the gasPrice is not set at that moment. This is maybe due to the order how web3 fills transaction defaults, but requires further checking too.

I'm going to investigate at least problem number 2 right now.

**Comment by KPrasch** [comment] 2021-02-26 02:04
> I'm going to investigate at least problem number 2 right now.

@cygnusv - What was the result of this investigation?

**Comment by KPrasch** [comment] 2022-03-25 22:55
Obsoleted by #2867

**Closed by KPrasch** 2022-03-25 22:55 UTC
Labels: Bug 🐞
