### ISSUE TITLE
Max gas price limit sometimes disregarded

### ISSUE THREAD

**Issue by svenski123** [nucypher/nucypher#2639] opened 2021-04-14 11:26 UTC
Maximum gas price as specified by the `--max-gas-price` is occasionally disregarded / ignored.

Ursula output from one example is below - in this case one transaction is submitted at the configured maximum gas price (70.1 gwei) at startup followed by repeated broadcast attempts over a number of hours when suddenly a transaction is submitted at a much higher gas price (100 gwei).

Nucypher version 4.8.2, python version 3.8.8, Alpine Linux 3.13 container, Centos 8.2.2004 host, podman version 1.6.4, kernel version 4.18.0-193.19.1.el8_2.x86_64
```
Verbose mode is enabled
Authenticating Ursula
Loaded Ursula 0x93eE1aC69b0c896A6a0972e59E5D25Be1C298c43 (mainnet)
Starting services
✓ Database Pruning
✓ Node Discovery (Mainnet)
✓ Worker is bonded to 0xBAc4Cf91090Fddbc72BC41531E092b7462041107
✓ Worker is funded with 0.211465296092459189 ETH
Broadcasting COMMITTONEXTPERIOD Transaction (0.0190055821 ETH @ 70.1 gwei)
TXHASH 0x53d3db990959e07885be2312c9dd30f1cd9bd449503b34ca2fa474b4c73fcd67
✓ Work Tracking
✓ Prometheus Exporter

Type 'help' or '?' for help
✓ Rest Server https://144.76.180.221:9151
Working ~ Keep Ursula Online!
Ursula(0xBAc4Cf9) >>> 
Broadcasting COMMITTONEXTPERIOD Transaction (0.023080425 ETH @ 70.1 gwei)
Broadcasting COMMITTONEXTPERIOD Transaction (0.023080425 ETH @ 70.1 gwei)
Broadcasting COMMITTONEXTPERIOD Transaction (0.023080425 ETH @ 70.1 gwei)
Broadcasting COMMITTONEXTPERIOD Transaction (0.0246880984 ETH @ 70.1 gwei)
Broadcasting COMMITTONEXTPERIOD Transaction (0.0246880984 ETH @ 70.1 gwei)
Broadcasting COMMITTONEXTPERIOD Transaction (0.0246880984 ETH @ 70.1 gwei)
Broadcasting COMMITTONEXTPERIOD Transaction (0.023080425 ETH @ 70.1 gwei)
Broadcasting COMMITTONEXTPERIOD Transaction (0.023080425 ETH @ 70.1 gwei)
Broadcasting COMMITTONEXTPERIOD Transaction (0.023080425 ETH @ 70.1 gwei)
Broadcasting COMMITTONEXTPERIOD Transaction (0.023080425 ETH @ 70.1 gwei)
Broadcasting COMMITTONEXTPERIOD Transaction (0.023080425 ETH @ 70.1 gwei)
Broadcasting COMMITTONEXTPERIOD Transaction (0.023080425 ETH @ 70.1 gwei)
Broadcasting COMMITTONEXTPERIOD Transaction (0.023080425 ETH @ 70.1 gwei)
Broadcasting COMMITTONEXTPERIOD Transaction (0.023080425 ETH @ 70.1 gwei)
Broadcasting COMMITTONEXTPERIOD Transaction (0.023080425 ETH @ 70.1 gwei)
Broadcasting COMMITTONEXTPERIOD Transaction (0.032925 ETH @ 100 gwei)
TXHASH 0x4b42b8e3db8cafa77f6ccf4cd7d81bf8d215b30914147eaa41f5ca5cc5e435c3
```

**Comment by derekpierre** [comment] 2021-05-21 14:48
Related to #2445 .

@cygnusv any inklings here of what may be causing this?

**Comment by chrisli30** [comment] 2021-05-23 03:59
I'm having the same issue. Could anybody help take a look at the cause?

**Comment by cygnusv** [comment] 2022-04-05 07:57
Out of scope at the moment. We reduced the TX surface a lot and this issue is very difficult to reproduce. We can reopen if there's a need

**Closed by cygnusv** 2022-04-05 07:57 UTC
Labels: Bug 🐞
