### ISSUE TITLE
BlockingIOError when running `known_nodes` from Ursula CLI

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#580] opened 2018-11-28 21:12 UTC
Running PR #562 , I get a BlockingIOError when I run `known_nodes` - 
https://sentry.io/nucypher/nucypher/issues/783364273/?query=is:unresolved

More detailed traceback:
```
eactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/Users/derek/.local/share/virtualenvs/nucypher-jOttX5sw/lib/python3.7/site-packages/twisted/internet/process.py", line 291, in doRead
    return fdesc.readFromFD(self.fd, self.dataReceived)
  File "/Users/derek/.local/share/virtualenvs/nucypher-jOttX5sw/lib/python3.7/site-packages/twisted/internet/fdesc.py", line 94, in readFromFD
    callback(output)
  File "/Users/derek/.local/share/virtualenvs/nucypher-jOttX5sw/lib/python3.7/site-packages/twisted/internet/process.py", line 295, in dataReceived
    self.proc.childDataReceived(self.name, data)
  File "/Users/derek/.local/share/virtualenvs/nucypher-jOttX5sw/lib/python3.7/site-packages/twisted/internet/_posixstdio.py", line 77, in childDataReceived
    self.protocol.dataReceived(data)
  File "/Users/derek/.local/share/virtualenvs/nucypher-jOttX5sw/lib/python3.7/site-packages/twisted/protocols/basic.py", line 572, in dataReceived
    why = self.lineReceived(line)
  File "/Users/derek/Documents/Github/repos/forks/kieran/nucypher/nucypher/cli/protocol.py", line 99, in lineReceived
    self.__commands[line]()
  File "/Users/derek/Documents/Github/repos/forks/kieran/nucypher/nucypher/cli/protocol.py", line 68, in paintKnownNodes
    paint_known_nodes(ursula=self.ursula)
  File "/Users/derek/Documents/Github/repos/forks/kieran/nucypher/nucypher/cli/painting.py", line 151, in paint_known_nodes
    click.secho(row_template.format(node.rest_url().ljust(20), node), fg=color_index[node_type])
  File "/Users/derek/.local/share/virtualenvs/nucypher-jOttX5sw/lib/python3.7/site-packages/click/termui.py", line 478, in secho
    return echo(message, file=file, nl=nl, err=err, color=color)
  File "/Users/derek/.local/share/virtualenvs/nucypher-jOttX5sw/lib/python3.7/site-packages/click/utils.py", line 260, in echo
    file.write(message)
builtins.BlockingIOError: [Errno 35] write could not complete without blocking
```

**Comment by cygnusv** [comment] 2018-11-28 21:20
What's weird is that the problem is with stdout.
This has happened before to me, and I have no idea why. I think it's not
specific to 562.

**Comment by KPrasch** [comment] 2018-11-28 21:21
Ooo - weird

**Comment by KPrasch** [comment] 2018-11-29 00:35
It looks like an error while console painting `  File "/Users/derek/Documents/Github/repos/forks/kieran/nucypher/nucypher/cli/painting.py", line 151, in paint_known_nodes`

... then writing to a file?

```
  File "/Users/derek/.local/share/virtualenvs/nucypher-jOttX5sw/lib/python3.7/site-packages/click/utils.py", line 260, in echo
    file.write(message)
builtins.BlockingIOError: [Errno 35] write could not complete without blocking
```

I wonder if this is being caused by `click.secho` execution in the twisted reactor.

**Comment by KPrasch** [comment] 2019-11-22 18:30
Closed in #562

**Closed by KPrasch** 2019-11-22 18:30 UTC
Labels: Bug 🐞, CLI

**Comment by joesixpack** [comment] 2020-02-02 01:06
Still happening:

![image](https://user-images.githubusercontent.com/23145642/73601373-1e1bf580-4515-11ea-9eb0-592f92bd6092.png)

**Comment by KPrasch** [comment] 2020-02-02 01:31
Can you confirm the version if NuCypher you are running?

**Comment by joesixpack** [comment] 2020-02-02 02:14
![image](https://user-images.githubusercontent.com/23145642/73601902-9dfa8d80-451e-11ea-9f85-eb61000f9094.png)

**Comment by KPrasch** [comment] 2020-02-02 02:47
Is this reliably reproducable?

**Comment by joesixpack** [comment] 2020-02-02 03:25
Yeah, happens on beta.2 as well.  Need to wait a while, it works right after startup, though.
