### ISSUE TITLE
Stake Tracker: "cannot unmarshal non-string into Go struct field TransactionArgs.chainId of type *hexutil.Big"

### ISSUE THREAD

**Issue by KevinVitale** [nucypher/nucypher#2901] opened 2022-04-02 19:14 UTC
**Describe the Bug**
My operator node continues to spew this **WARNING**:

> "cannot unmarshal non-string into Go struct field TransactionArgs.chainId of type *hexutil.Big"

**To Reproduce**
Run an PRE node

**Traceback or Screenshots (Optional)**
```sh
[stake-tracker#warn] Unhandled error during work tracking (#19): 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/twisted/internet/base.py", line 1315, in run\n    self.mainLoop()\n  File "/usr/local/lib/python3.8/site-packages/twisted/internet/base.py", line 1325, in mainLoop\n    reactorBaseSelf.runUntilCurrent()\n  File "/usr/local/lib/python3.8/site-packages/twisted/internet/base.py", line 991, in runUntilCurrent\n    call.func(*call.args, **call.kw)\n  File "/usr/local/lib/python3.8/site-packages/twisted/internet/task.py", line 251, in __call__\n    d = maybeDeferred(self.f, *self.a, **self.kw)\n--- <exception caught here> ---\n  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 190, in maybeDeferred\n    result = f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/nucypher/blockchain/eth/token.py", line 399, in _do_work\n    txhash = self._fire_commitment()\n  File "/usr/local/lib/python3.8/site-packages/nucypher/blockchain/eth/token.py", line 447, in _fire_commitment\n    txhash = self.worker.confirm_address(fire_and_forget=True)  # < --- blockchain WRITE\n  File "/usr/local/lib/python3.8/site-packages/nucypher/blockchain/eth/actors.py", line 344, in confirm_address\n    txhash_or_receipt = self.application_agent.confirm_operator_address(self.transacting_power, fire_and_forget=fire_and_forget)\n  File "/usr/local/lib/python3.8/site-packages/nucypher/blockchain/eth/decorators.py", line 105, in wrapped\n    return func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/nucypher/blockchain/eth/agents.py", line 546, in confirm_operator_address\n    receipt = self.blockchain.send_transaction(contract_function=contract_function,\n  File "/usr/local/lib/python3.8/site-packages/nucypher/blockchain/eth/decorators.py", line 105, in wrapped\n    return func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/nucypher/blockchain/eth/interfaces.py", line 662, in send_transaction\n    txhash_or_receipt = self.sign_and_broadcast_transaction(transacting_power=transacting_power,\n  File "/usr/local/lib/python3.8/site-packages/nucypher/blockchain/eth/interfaces.py", line 574, in sign_and_broadcast_transaction\n    signed_raw_transaction = transacting_power.sign_transaction(transaction_dict)\n  File "/usr/local/lib/python3.8/site-packages/nucypher/crypto/powers.py", line 190, in sign_transaction\n    return self._signer.sign_transaction(transaction_dict=transaction_dict)\n  File "/usr/local/lib/python3.8/site-packages/nucypher/blockchain/eth/signers/software.py", line 102, in sign_transaction\n    signed_raw_transaction = self.__client.sign_transaction(transaction_dict=transaction_dict)\n  File "/usr/local/lib/python3.8/site-packages/nucypher/blockchain/eth/clients.py", line 460, in sign_transaction\n    result = self.w3.eth.signTransaction(transaction_dict)\n  File "/usr/local/lib/python3.8/site-packages/web3/module.py", line 44, in caller\n    result = w3.manager.request_blocking(method_str, params, error_formatters)\n  File "/usr/local/lib/python3.8/site-packages/web3/manager.py", line 158, in request_blocking\n    raise ValueError(response["error"])\nbuiltins.ValueError: {\'code\': -32602, \'message\': \'invalid argument 0: json: cannot unmarshal non-string into Go struct field TransactionArgs.chainId of type *hexutil.Big\'}\n'
```

**System (please complete the following information):**
 - OS Version: recent Ubuntu LTS
 - Nucypher Version: 6
 - Ethereum Node Version: latest Geth

**Comment by KPrasch** [comment] 2022-04-02 19:16
More specifically to reproduce: run a PRE node using a geth node as a signer and set as the payment provider (implicit default if no keystore is provided).

**Comment by KPrasch** [comment] 2022-04-02 19:58
related to https://github.com/nucypher/nucypher/issues/2602

**Comment by KPrasch** [comment] 2022-10-28 10:08
duplicate of https://github.com/nucypher/nucypher/issues/2602

**Closed by KPrasch** 2022-10-28 10:08 UTC
Labels: Bug :bug:
