### ISSUE TITLE
Not all tests pass in docker scenario 

### ISSUE THREAD

**Issue by seniorjoinu** [nucypher/nucypher#945] opened 2019-04-24 09:21 UTC
Following the instructions from https://github.com/nucypher/nucypher/blob/master/dev/docker/README.md

Logs are here: https://pastebin.ubuntu.com/p/JXVd583DHG/

Is this OK?

I'm on ubuntu 18.04 x64

**Comment by KPrasch** [comment] 2019-12-03 01:48
Thanks for the report, I was unable to reproduce the exact errors shown in the pastebin example above, although there are 12 unrelated failures, which are known issues when running the entire test suite independent of docker.  I surmise this issue has been mostly resolved by a prior release, and am marking it wont-fix, unless there is a docker-specific problem to re-open it.

For the record, here are the commands I used on `f99d60b8625087552e74d740661dbc68d8c88012`:

`docker-compose -f dev/docker/docker-compose.yml build `
`docker-compose -f dev/docker/docker-compose.yml run nucypher-dev pytest `

**Closed by KPrasch** 2019-12-03 01:48 UTC
Labels: wontfix
