### ISSUE TITLE
Ursula uses KFrag.verify() when she receives KFrags from Alice

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#184] opened 2018-03-28 06:58 UTC
Ursula has to call the method `KFrag.verify()` offered by pyUmbral to check the validity of the kFrag given by Alice.

**Comment by jMyles** [comment] 2018-03-28 08:57
Right right right.  :+1:

**Comment by jMyles** [comment] 2018-06-01 18:44
Duplicate of #167

**Closed by jMyles** 2018-06-01 18:44 UTC
