### ISSUE TITLE
OpenEthereum is not a supported ethereum client

### ISSUE THREAD

**Issue by ronmnm** [nucypher/nucypher#2372] opened 2020-10-15 12:44 UTC
When trying to connect to archive node, it fails with error:
```
     self.client = EthereumClient.from_w3(w3=self.w3)
File "/home/pool-worker/nucypher-venv/lib/python3.6/site-packages/nucypher/blockchain/eth/clients.py", line 209, in from_w3
    raise NotImplementedError(f'{w3.clientVersion} is not a supported ethereum client')
NotImplementedError: OpenEthereum//v3.0.1-stable-8ca8089-20200601/x86_64-unknown-linux-gnu/rustc1.43.1 is not a supported ethereum client
```

 - OS Version: Ubuntu 16
 - Nucypher Version: version 4.0.0
 - Ethereum Node Version:  OpenEthereum v3.0.1-stable-8ca8089-20200601

**Comment by KPrasch** [comment] 2020-10-15 19:27
Duplicate of #2298

**Comment by KPrasch** [comment] 2024-02-20 15:49
tracking in #3460

**Closed by KPrasch** 2024-02-20 15:49 UTC
Labels: Enhancement, Platform
