### ISSUE TITLE
TreasureMap storage

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2125] opened 2020-07-07 03:05 UTC
We are still only using an in-memory dictionary to store TreasureMaps.

We talked about this on the call; @tuxxy expressed an interest in applying a quick solution to use the database functionality up which they've been standing.

**Comment by KPrasch** [comment] 2020-09-01 19:01
duplicate of #2134

**Closed by KPrasch** 2020-09-01 19:01 UTC
Labels: Data Storage, Ursula :woman_astronaut:
