### ISSUE TITLE
WS provider: cannot call recv while another coroutine exception

### ISSUE THREAD

**Issue by tylerdow** [nucypher/nucypher#1859] opened 2020-04-08 08:14 UTC
**Describe the Bug**
I just run my node and see this in my log after few minutes of activity. Node running as a service.

**To Reproduce**
I just ran my node

**Traceback or Screenshots (Optional) **
nucypher[29584]: Unhandled error in Deferred:
nucypher[29584]: Traceback (most recent call last):
nucypher[29584]:   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
nucypher[29584]:     self.run()
nucypher[29584]:   File "/usr/lib/python3.6/threading.py", line 864, in run
nucypher[29584]:     self._target(*self._args, **self._kwargs)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
nucypher[29584]:     task()
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
nucypher[29584]:     task()
nucypher[29584]: --- <exception caught here> ---
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
nucypher[29584]:     result = inContext.theWork()
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
nucypher[29584]:     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
nucypher[29584]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
nucypher[29584]:     return func(*args,**kw)
nucypher[29584]:   File "/home/nucypher/source/nucypher/nucypher/network/server.py", line 207, in learn_about_announced_nodes
nucypher[29584]:     registry=this_node.registry)
nucypher[29584]:   File "/home/nucypher/source/nucypher/nucypher/network/nodes.py", line 1218, in verify_node
nucypher[29584]:     self.validate_metadata(registry=registry)
nucypher[29584]:   File "/home/nucypher/source/nucypher/nucypher/network/nodes.py", line 1178, in validate_metadata
nucypher[29584]:     self.validate_worker(registry=registry)
nucypher[29584]:   File "/home/nucypher/source/nucypher/nucypher/network/nodes.py", line 1159, in validate_worker
nucypher[29584]:     if self._staker_is_really_staking(registry=registry):  # <-- Blockchain CALL
nucypher[29584]:   File "/home/nucypher/source/nucypher/nucypher/network/nodes.py", line 1128, in _staker_is_really_staking
nucypher[29584]:     stake_next_period = staking_agent.get_locked_tokens(staker_address=self.checksum_address, periods=1)
nucypher[29584]:   File "/home/nucypher/source/nucypher/nucypher/blockchain/eth/decorators.py", line 74, in wrapped
nucypher[29584]:     return func(*args, **kwargs)
nucypher[29584]:   File "/home/nucypher/source/nucypher/nucypher/blockchain/eth/agents.py", line 345, in get_locked_tokens
nucypher[29584]:     return self.contract.functions.getLockedTokens(staker_address, periods).call()
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/contract.py", line 911, in call
nucypher[29584]:     **self.kwargs
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/contract.py", line 1436, in call_contract_function
nucypher[29584]:     return_data = web3.eth.call(call_transaction, block_identifier=block_id)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/eth_utils/functional.py", line 45, in inner
nucypher[29584]:     return callback(fn(*args, **kwargs))
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/eth.py", line 430, in call
nucypher[29584]:     [transaction, block_identifier],
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/manager.py", line 149, in request_blocking
nucypher[29584]:     response = self._make_request(method, params)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/manager.py", line 128, in _make_request
nucypher[29584]:     return request_func(method, params)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/cache.py", line 134, in middleware
nucypher[29584]:     return make_request(method, params)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/cache.py", line 427, in middleware
nucypher[29584]:     response = make_request(method, params)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/cache.py", line 247, in middleware
nucypher[29584]:     return make_request(method, params)
nucypher[29584]:   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
nucypher[29584]:     return self.func(*args, **kwargs)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
nucypher[29584]:     response = make_request(method, params)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
nucypher[29584]:     return make_request(method, params)
nucypher[29584]:   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
nucypher[29584]:     return self.func(*args, **kwargs)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 73, in apply_formatters
nucypher[29584]:     response = make_request(method, formatted_params)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 33, in middleware
nucypher[29584]:     response = make_request(method, params)
nucypher[29584]:   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
nucypher[29584]:     return self.func(*args, **kwargs)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 73, in apply_formatters
nucypher[29584]:     response = make_request(method, formatted_params)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
nucypher[29584]:     result = make_request(method, params)
nucypher[29584]:   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
nucypher[29584]:     return self.func(*args, **kwargs)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 73, in apply_formatters
nucypher[29584]:     response = make_request(method, formatted_params)
nucypher[29584]:   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
nucypher[29584]:     return self.func(*args, **kwargs)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 73, in apply_formatters
nucypher[29584]:     response = make_request(method, formatted_params)
nucypher[29584]:   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
nucypher[29584]:     return self.func(*args, **kwargs)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 75, in apply_formatters
nucypher[29584]:     response = make_request(method, params)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/providers/websocket.py", line 137, in make_request
nucypher[29584]:     return future.result()
nucypher[29584]:   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
nucypher[29584]:     return self.__get_result()
nucypher[29584]:   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
nucypher[29584]:     raise self._exception
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/web3/providers/websocket.py", line 125, in coro_make_request
nucypher[29584]:     timeout=self.websocket_timeout
nucypher[29584]:   File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
nucypher[29584]:     return fut.result()
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/websockets/protocol.py", line 474, in recv
nucypher[29584]:     "cannot call recv while another coroutine "

**System (please complete the following information):**
 - OS Version: Ubuntu 18.04 LTS
 - Nucypher Version: 2.1.0-beta.2
 - Ethereum Node Version:  1.9.7-stable on external node via websocket

**Comment by jMyles** [comment] 2020-09-11 21:43
@KPrasch, @derekpierre: It's increasingly looking like, although they are caused by different logic, that #2188 is essentially a duplicate of this.

My idea that we discussed - of creating a mechanism of backpressure by using `ensureDeferred` and adding a callback to handle each provider call - is hampered by my confusion over this problem: https://stackoverflow.com/questions/63854639/how-can-i-ensuredeferred-a-coroutine-which-awaits-asyncio-wait

**Comment by KPrasch** [comment] 2020-10-07 15:06
This issue is still under investigation and scoping, however as a work around, you can run nucypher using an *http(s)* web3 provider instead of *wss* until there is a fix.

**Comment by KPrasch** [comment] 2022-03-25 22:38
There are no plans to support websocket ethereum providers.  Use https!

**Closed by KPrasch** 2022-03-25 22:38 UTC
Labels: Bug 🐞, Ursula :woman_astronaut:
