### ISSUE TITLE
This does not appear to be a VariableLengthBytestring exception

### ISSUE THREAD

**Issue by tylerdow** [nucypher/nucypher#1860] opened 2020-04-08 08:16 UTC
**Describe the Bug**
I just run my node and see this in my log after few minutes of activity. Node running as a service.

**To Reproduce**
I just ran my node

**Traceback or Screenshots (Optional) **
nucypher[29584]: Unhandled error in Deferred:
nucypher[29584]: Traceback (most recent call last):
nucypher[29584]:   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
nucypher[29584]:     self.run()
nucypher[29584]:   File "/usr/lib/python3.6/threading.py", line 864, in run
nucypher[29584]:     self._target(*self._args, **self._kwargs)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
nucypher[29584]:     task()
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
nucypher[29584]:     task()
nucypher[29584]: --- <exception caught here> ---
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
nucypher[29584]:     result = inContext.theWork()
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
nucypher[29584]:     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
nucypher[29584]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
nucypher[29584]:     return func(*args,**kw)
nucypher[29584]:   File "/home/nucypher/source/nucypher/nucypher/network/server.py", line 203, in learn_about_announced_nodes
nucypher[29584]:     node.mature()
nucypher[29584]:   File "/home/nucypher/source/nucypher/nucypher/network/nodes.py", line 268, in mature
nucypher[29584]:     mature_node = self.finish()
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/bytestring_splitter/__init__.py", line 53, in finish
nucypher[29584]:     return self._receiver(**finished_values, **self._additional_kwargs)
nucypher[29584]:   File "/home/nucypher/source/nucypher/nucypher/characters/lawful.py", line 1420, in from_processed_bytes
nucypher[29584]:     domains_vbytes = VariableLengthBytestring.dispense(processed_objects.pop('domains'))
nucypher[29584]:   File "/home/nucypher/nucypher-venv/lib/python3.6/site-packages/bytestring_splitter/__init__.py", line 422, in dispense
nucypher[29584]:     raise BytestringSplittingError("This does not appear to be a VariableLengthBytestring, or is not the correct length.")
nucypher[29584]: bytestring_splitter.BytestringSplittingError: This does not appear to be a VariableLengthBytestring, or is not the correct length.

**System (please complete the following information):**
 - OS Version: Ubuntu 18.04 LTS
 - Nucypher Version: 2.1.0-beta.2
 - Ethereum Node Version:  1.9.7-stable on external node via websocket

**Comment by KPrasch** [comment] 2020-04-08 13:31
Duplicate of #1843

**Closed** 2020-04-10 22:15 UTC
Labels: Bug 🐞, duplicate
