### ISSUE TITLE
Ursula blocks forever on startup with 0 ETH balance 

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2983] opened 2022-10-06 17:31 UTC
Replaces #2948

**Comment by derekpierre** [comment] 2023-09-20 18:47
Of course the issue is now 0 MATIC for 7.0.0.

Hazy on the original details, but for 7.0.0 the node does need funding to ensure not just potential setting of the provider public key on the Coordinator on startup, but also ritual participation (post transcript/aggregations) for the DKG ceremony.

Perhaps we should close this, @KPrasch wdyt?

**Comment by derekpierre** [comment] 2024-02-20 14:33
This was an issue in the old non-TACo paradigm, because after the node first starts up and it performs the confirm operator tx, the node no longer needed to perform any more transactions, yet we always checked for non-zero funding on startup.

In the TACo paradigm, the node should not ever have `0 MATIC` since they need MATIC for potential DKG ritual ceremonies. Checking for non-zero funding on startup is now a requirement.

**Closed by derekpierre** 2024-02-20 14:33 UTC
Labels: Bug :bug:, Can we close this?
