### ISSUE TITLE
Prometheus metric for ursula_active_stake fails to update

### ISSUE THREAD

**Issue by leslieonline27** [nucypher/nucypher#2414] opened 2020-10-30 10:52 UTC
**Describe the Bug**
The Prometheus metric for `ursula_active_stake` fails to update, and the following is seen in the worker logs:
```
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/base.py", line 1292, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/nucypher/utilities/prometheus/metrics.py", line 147, in collect_prometheus_metrics
    collector.collect()
  File "/usr/local/lib/python3.7/site-packages/nucypher/utilities/prometheus/collector.py", line 76, in collect
    self._collect_internal()
  File "/usr/local/lib/python3.7/site-packages/nucypher/utilities/prometheus/collector.py", line 140, in _collect_internal
    locked = staking_agent.get_locked_tokens(staker_address=self.ursula.checksum_address, periods=1)
  File "/usr/local/lib/python3.7/site-packages/nucypher/blockchain/eth/decorators.py", line 105, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nucypher/blockchain/eth/agents.py", line 373, in get_locked_tokens
    return NuNits(self.contract.functions.getLockedTokens(staker_address, periods).call())
  File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 964, in call
    **self.kwargs
  File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 1499, in call_contract_function
    return_data = web3.eth.call(call_transaction, block_identifier=block_id)
  File "/usr/local/lib/python3.7/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/web3/eth.py", line 434, in call
    [transaction, block_identifier],
  File "/usr/local/lib/python3.7/site-packages/web3/manager.py", line 153, in request_blocking
    raise ValueError(response["error"])
builtins.ValueError: {'code': -32000, 'message': 'execution aborted (timeout = 5s)'}
```

**To Reproduce**
I have not been able to reproduce

**System (please complete the following information):**
 - OS Version: docker container nucypher/nucypher:v4.1.0
 - Nucypher Version: v4.1.0
 - Ethereum Node Version:  Infura

On restarting the node, the metric appears to update correctly as the previous value has been incremented by the expected amount.  It might also be worth noting that `eth` requests drop off a cliff at about the same time as this error occurs, and stay that way.

**Comment by cygnusv** [comment] 2021-01-04 12:57
@derekpierre Trying to triage this issue. Do you have an idea of what can be producing this? I say we tentatively close this unless we have an idea of a potential cause or fix for this, or at the very least, a way to reproduce. What do you think?

**Comment by derekpierre** [comment] 2021-01-04 15:01
Unclear what caused the original problem, but it does not seem reproducible. The `ursula_active_stake` metric works well in our internal staged grafana and prometheus dashboard that uses the dashboard created by p2p (https://github.com/p2p-org/nucypher-monitoring). I'll close for now.

@leslieonline27 If the problem is observed again please open a new issue.

**Closed by derekpierre** 2021-01-04 15:01 UTC
Labels: Bug 🐞
