### ISSUE TITLE
Conditional PRE service

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1276] opened 2019-08-27 13:03 UTC
We currently expect `Ursula` to perform PRE service pursuant to any active `Policy`, without any further conditions.

However, conditional service is a common feature request.  It's not even entirely obvious how this might work - will there be a subset of conditions which `Alice` can specify?  Will we craft a micro-language for evaluating these conditions?  What if a condition is unduly onerous (ie, encode this 18GB video file and determine if the number of frames which are >10% red is great than x)?  Surely Ursula isn't responsible for arbitrary computation under the guise of a PRE condition?

**Completion condition**: Ursula performs or forebears PRE service based on an arbitrary on-chain boolean value.

**Comment by cygnusv** [comment] 2019-08-27 13:11
Continuing this idea, how about Alice can set up a smart contract which Ursulas can check in order to enforce access control? Alice can use this smart contract to revoke indefinitely or just during some periods, to grant access based on payments, etc.

**Comment by mswilkison** [comment] 2019-09-02 21:31
The simplest completion condition for this is to assume a 3rd party oracle evaluates the condition.

**Comment by tuxxy** [comment] 2019-09-04 10:33
The deliverable that I immediately envision for minimum-viable condition programming is attaching Alice-supplied metadata to the policy (perhaps via JSON) with "re-encryption constraint variables" that allow exceptionally limited evaluation.

Consider the following problem that requires conditional re-encryption from the staking KMS use-case:
```
Alice wants to be able to use NuCypher as a KMS for their Cosmos staking nodes.
However, they want to prevent double-signing.
Presently, NuCypher has no method of preventing a so-called "double access".
```

With the introduction of "re-encryption constraint variables" (let's call them RCVs for short), we can offer extremely limited logic evaluation and offer a solution to the double-signature problem. RCVs are variables that can be optionally included in policy metadata to allow constraint design during re-encryption requests. They should have hard-coded and well-documented behavior. Let's go into more details on a RCV that is, both, simple to develop and exceptionally flexible in utility -- an access counter.

An access counter is a RCV that gets incremented by one at every successful re-encryption request. The behavior to evaluate the RCV is hard-coded to Ursula and will be performed upon every successful re-encryption. It's defined in a metadata field when Alice initially creates a policy. Whenever Bob successfully requests a re-encryption, Ursula updates the access counter metadata field. Let's see an example of what this metadata may look like at policy creation:

```
{
    "access_counter": 0,
     ...
}
```

Now that we've discussed what this policy metadata may look like, let's explore leveraging it to solve the double-signing problem via constraint programming.

A constraint is an expression that should be interpreted as a requirement for re-encryption to occur. If the constraint is not satisfied, Ursula will deny re-encryption. It can be defined in the same policy metadata described above. Let's take a look at what this may be:

```
{
    "access_counter": 0,
    "constraints": [
         "access_counter < reencryption_num",
    ],
    ...
}
```

In the above example, the added constraints field contains a string defining a boolean expression, `access_counter < reencryption_num`. Immediately, the question that comes to mind is, "Where does the `reencryption_num` variable get defined?" In this proposal, all constraints are of the following form:

`RCV <boolean operation> request_variable`

Breaking down our example expression, we see the RCV, the leftmost part of the expression, being called as `access_counter`. In the middle, we have our boolean operation `<`. Finally, the rightmost part of the expression is our request variable named as `reencryption_num`.

With the following constraint we can expect the following behaviors from Ursula:

1. Ursula will verify the re-encryption request as normal and check for constraints in her own metadata.
2. If constraints exist, she will further validate the re-encryption request by checking the request for the request variable described in the constraint. If the request _does not_ contain the request variable defined in the constraint, Ursula will deny re-encryption.
3. If the request variable is valid, Ursula will evaluate the constraint condition. If the constraint condition is _false_, Ursula will deny re-encryption.
4. If the constraint condition is _true_, Ursula will proceed with re-encryption as normal, evaluating any other constraint conditions that may exist.
5. After re-encryption has been performed successfully, Ursula will update the RCVs in her policy metadata, ready for another request. Any errors result in the re-encryption process halting as normal with no changes to metadata.

The example constraint provides a non-perfect solution to the double-signing problem, but it paints a picture of how we may leverage our new RCVs and constraint programming to build a conditional access control system based on tight, semi-arbitrary definitions.

Though we've provided a solution to the double-signing problem, we acknowledge that there are faults in this specific approach, but will not enumerate them in this proposal. Instead, we leave a more complete solution to be detailed in a separate proposal. We suggest that a future proposal utilize a similar approach defined here, but additionally proposing the creation of a new RCV that utilizes a time-since-last-access approach.

**Comment by michwill** [comment] 2019-09-05 12:20
@mswilkison Third-party oracles are fine, but they become problematic once we start enforcing re-encryptions. If an oracle tells that the condition is "true" for one half of the network and "false" for the other half, you may have honest Ursulas slashed.
On-chain function for that is superior in this regard

**Comment by michwill** [comment] 2019-09-06 23:21
Good question - should the condition be reproducible by an external third party? I would say yes, because we want to evenrually slash Ursulas for not doing their jobs. But it'd preclude some good conditions (such as ones involving the number of re-encryptions).

In the simple form, I can imagine telling _any_ contract and a call-only method when re-encrypting (then Ursula would need to also return current ETH block number and hash in her opinion, so that everyone can check if that condition is indeed satisfied).

But what do we want here? Simple (e.g. ranges of times, on-payment etc) conditions can be expressed by this approach, but something fast, esp. preventing double-signing probably not.

Or we can do an approach in line with what @tuxxy  is proposing, but then it'd be impossible (or maybe I'm wrong?) to enforce Ursulas to complete that job.

**Comment by KPrasch** [comment] 2020-12-22 23:57
bump @derekpierre @arjunhassard

**Comment by jdbertron** [comment] 2021-12-07 04:53
> @mswilkison Third-party oracles are fine, but they become problematic once we start enforcing re-encryptions. If an oracle tells that the condition is "true" for one half of the network and "false" for the other half, you may have honest Ursulas slashed. On-chain function for that is superior in this regard

Could you have Alice's contract produce the ZKSNARK needed to evaluate the condition. Then have the Ursulas publish a commitment to the effect they have observed it, so they have no option after the evaluation ?

**Comment by KPrasch** [comment] 2022-10-28 09:12
Closed by https://github.com/nucypher/nucypher/pull/2960

**Closed by KPrasch** 2022-10-28 09:12 UTC
Labels: Protocol, Ursula :woman_astronaut:, conditional PRE

**Comment by mastercyb** [comment] 2022-10-31 02:28
Amazing news. Do you have some examples or docs on this feature?
