### ISSUE TITLE
Implement revocation confirmations from Ursula

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#569] opened 2018-11-21 19:46 UTC
When Ursula accepts a `Revocation` from Alice, she should sign the Revocation (w/ signature) and send it back as confirmation that she agreed to revoke the arrangement.

**Comment by KPrasch** [comment] 2018-12-03 23:01
Duplicate of #504

**Comment by KPrasch** [comment] 2019-11-22 18:33
Dupe of #504

**Closed by KPrasch** 2019-11-22 18:33 UTC
Labels: Network, Scoping
